sudo: required
services:
  - docker

scripts:
  - docker build -t jmeroth/node .
  - docker images jmeroth/node

before_deploy:
  - docker login -u DOCKER_USERNAME -p DOCKER_PASSWORD

deploy:
  provider: script
  script: docker push jmeroth/node
  on:
    branch: master